# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options
variables:
  GITLAB_CI_IMAGE_ALPINE: 'alpine:3.16.1'
  GITLAB_CI_SIGN_OFF_EXCLUDE: '804cc6ed1a87660d762d8d997db7aaf6b98074a8'

stages:
  - static
  - test

before_script:
  - git clone --branch master https://gitlab.com/kicad/libraries/kicad-library-utils.git

after_script:


footprint_test:
  image: python:3.10
  stage: test
  script:
    #- for f in $(git diff --name-only ${CI_COMMIT_SHA}..origin/master | grep kicad_mod); do ./kicad-library-utils/pcb/check_kicad_mod.py $f -v; done
    - sed -i 's/KICAD8_3DMODEL_DIR/LSF_KICAD_LIB/g' ./kicad-library-utils/klc-check/rules_footprint/F9_3.py
    - ./kicad-library-utils/klc-check/check_footprint.py -v lsf-kicad-lib.pretty/$(ls lsf-kicad-lib.pretty/*|grep -iv LOGO|sed 's/\n/ /'g)
  only:
    changes:
      - lsf-kicad-lib.pretty/*.kicad_mod


library_test:
  image: python:3.10
  stage: test
  script:
    - ./kicad-library-utils/klc-check/check_symbol.py *.kicad_sym -v
  only:
    changes:
      - "*.kicad_sym"
      - "*.dcm"

# 'static' stage
sign_off:
  stage: static
  needs: []
  image: ${GITLAB_CI_IMAGE_ALPINE}
  before_script:
    - apk add --no-cache git
  script: >-
    git log
    --grep "^Signed-off-by: .\+<.\+\(@\| at \).\+\(\.\| dot \).\+>$"
    --invert-grep
    --format="Detected commit '%h' with missing or bad sign-off! Please read 'CONTRIBUTING.md'."
    --exit-code
    "$(rev=$(git rev-parse -q --verify "$GITLAB_CI_SIGN_OFF_EXCLUDE^{commit}") && echo "$rev..")"
